<?php

namespace Lkn\BBPix\App\Pix\Entity;

/**
 * First, you need to run one of those methods: create, fromWhmcsTransId, fromApi.
 * Then, you will be able to call getTransIdForWhmcs and getApiTransId.
 *
 * @since 1.2.0
 */
final class PixTaxId
{
    private const DETERMINISTIC_TXID_PREFIX = 'LKN';

    private const DETERMINISTIC_INVOICE_LENGTH = 10;

    private const DETERMINISTIC_SUFFIX_LENGTH = 13;

    /**
     * random suffix generated by this class.
     *
     * @since 1.0.0
     * @var string
     */
    public readonly string $suffix;

    /**
     * One of following: CREATED, PAID, REFUNDED.
     *
     * @since 1.0.0
     * @var string
     */
    public readonly string $prefix;

    /**
     * WHMCS invoice ID.
     *
     * @since 1.0.0
     * @var int
     */
    public readonly int $invoiceId;

    public static function create(string $invoiceId, string $prefix): self
    {
        $txId = new PixTaxId();

        $txId->setInvoiceId((int) $invoiceId);
        $txId->setPrefix($prefix);
        $txId->setSuffix();

        return $txId;
    }

    /**
     * @since 1.2.0
     *
     * @param string $transacId the WHMCS full transaction ID. PAGO|CRIADOxRANDOM_STRING
     * @param int    $invoiceId
     *
     * @return PixTaxId
     */
    public static function fromWhmcsTransId(string $transacId, int $invoiceId): PixTaxId
    {
        $exploded = explode('x', $transacId, 3);

        $txId = new PixTaxId();

        $txId->setInvoiceId($invoiceId);
        $txId->setPrefix($exploded[0]);
        $txId->setSuffix($exploded[1]);

        return $txId;
    }

    /**
     * @since 1.2.0
     *
     * @param string $prefix  the new prefix for the taxId. PAGO or CRIADO.
     * @param string $apiTxId the txId sent to the API and is returned by it.
     *                        It is the InvoiceIDxRandomSuffix
     *
     * @return self
     */
    public static function fromApi(string $prefix, string $apiTxId): self
    {
        $normalizedTxid = strtoupper(trim($apiTxId));

        if (self::isDeterministicTxid($normalizedTxid)) {
            return self::fromDeterministicTxid($normalizedTxid, $prefix);
        }

        $exploded = explode('x', $normalizedTxid, 2);

        $txId = new PixTaxId();

        $txId->setInvoiceId((int) $exploded[0]);
        $txId->setSuffix($exploded[1]);
        $txId->setPrefix($prefix);

        return $txId;
    }

    /**
     * Builds a WHMCS transaction id from a deterministic automatic txid.
     *
     * Automatic flow txids are generated as LKN + padded invoice + hash.
     * For traceability, we keep this txid as the CRIADOx suffix.
     */
    public static function fromDeterministicTxid(string $txid, string $prefix = 'CRIADO'): self
    {
        $normalizedTxid = strtoupper(trim($txid));
        $invoiceId = self::extractInvoiceIdFromDeterministicTxid($normalizedTxid);

        if ($invoiceId <= 0) {
            throw new \InvalidArgumentException('Txid deterministico invalido.');
        }

        $txId = new PixTaxId();

        $txId->setInvoiceId($invoiceId);
        $txId->setPrefix($prefix);
        $txId->setSuffix($normalizedTxid);

        return $txId;
    }

    private static function extractInvoiceIdFromDeterministicTxid(string $txid): int
    {
        if (preg_match(self::getDeterministicTxidPattern(), $txid, $matches) !== 1) {
            return 0;
        }

        $invoice = ltrim($matches[1], '0');

        return (int) ($invoice === '' ? '0' : $invoice);
    }

    private static function isDeterministicTxid(string $txid): bool
    {
        return preg_match(self::getDeterministicTxidPattern(), $txid) === 1;
    }

    private static function getDeterministicTxidPattern(): string
    {
        return sprintf(
            '/^%s(\d{%d})[A-Z0-9]{%d}$/',
            self::DETERMINISTIC_TXID_PREFIX,
            self::DETERMINISTIC_INVOICE_LENGTH,
            self::DETERMINISTIC_SUFFIX_LENGTH
        );
    }

    public function setPrefix(string $prefix): self
    {
        $this->prefix = $prefix;

        return $this;
    }

    public function setInvoiceId(int $invoiceId): self
    {
        $this->invoiceId = $invoiceId;

        return $this;
    }

    public function setSuffix(?string $suffix = null): self
    {
        $this->suffix = $suffix === null ? bin2hex(random_bytes(13)) : $suffix;

        return $this;
    }

    /**
     * Returns the WHMCS transaction id for WHMCS.
     *
     * @since 1.0.0
     *
     * @return string PAGO|CRIADOxRANDOM_STRING
     */
    public function getTransIdForWhmcs(?string $suffix = null): string
    {
        return $this->prefix . 'x' . $this->suffix . ($suffix ? "x{$suffix}" : '');
    }

    /**
     * Returns the taxid for the Pix API.
     *
     * @since 1.0.0
     *
     * @return string INVOICE_IDxRANDOM_STRING
     */
    public function getApiTransId(): string
    {
        if (self::isDeterministicTxid($this->suffix)) {
            return $this->suffix;
        }

        return $this->invoiceId . 'x' . $this->suffix;
    }
}
